name: Build PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/FiraSans-Regular.ttf
            ./fonts/Inconsolata-Regular.ttf
      - name: Convert ebook
        uses: jensvog/ebook-convert-action@v1
        with:
          in: main.pdf
          out: main.epub
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: EPUB
          path: main.epub
